apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://{kube-apiserver-hostname}
  name: nixops-k8s
contexts:
- context:
    cluster: nixops-k8s
    user: nixops-admin
  name: nixops-k8s
current-context: nixops-k8s
kind: Config
preferences: {}
users:
- name: nixops-admin
  user:
    as-user-extra: {}
    password: kubernetes
    username: admin